services:
  # Prowlarr for indexers sync
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./prowlarr/config:/config
      - ./prowlarr/data:/data # Simplifié pour tous les services
    networks:
      - internal
    ports:
      - 9696:9696
    restart: unless-stopped
  
  # FlareSolverr for Cloudflare
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/London
    networks:
      - internal
    ports:
      - "8191:8191"
    restart: unless-stopped
  
  # Radarr for movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./radarr/config:/config
      - ./radarr/data:/data
      - ./media/movies:/media/movies
      - ./downloads:/downloads
    networks:
      - internal
    ports:
      - 7878:7878
    restart: unless-stopped
  
  # Sonarr for TV shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/data:/data
      - ./media/tv:/media/tv
      - ./downloads:/downloads
    networks:
      - internal
    ports:
      - 8989:8989
    restart: unless-stopped
  
  # qBittorrent for torrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
      - ./media/movies:/media/movies
      - ./media/tv:/media/tv
      - ./media/music:/media/music
      - ./media/ebooks:/media/ebooks
    networks:
      - internal
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  # Jellyseerr for media request
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
    networks:
      - internal
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr/config:/app/config
    restart: unless-stopped

  # Jellyfin for media server
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    group_add:
      - "122"
    networks:
      - internal
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900
    environment:
      - VERSION=latest
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cahe
      - ./media/movies:/media/movies
      - ./media/tv:/media/tv
      - ./media/music:/media/music
      - ./media/ebooks:/media/ebooks

  # Wizarr for invite management
  wizarr:
      container_name: wizarr
      image: ghcr.io/wizarrrr/wizarr:latest
      networks:
        - internal
      ports:
        - 5690:5690
      volumes:
        - ./wizarr/database:/data/database

  # Requestrr for Discord
  requestrr:
    container_name: requestrr
    image: thomst08/requestrr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    networks:
      - internal
    ports:
      - 4545:4545
    volumes:
      - ./requestrr/config:/root/config
    restart: unless-stopped

  # Cloudflare Tunnel for remote access
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    networks:
      - internal
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN

  # Watchtower for auto update
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: unless-stopped

  # Lidarr for music
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./lidarr/config:/config
      - ./lidarr/data:/data
      - ./media/music:/media/music
      - ./downloads:/downloads
    ports:
      - 8686:8686
    networks:
      - internal
    restart: unless-stopped

  # Readarr for ebooks
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./readarr/config:/config
      - ./readarr/data:/data
      - ./downloads:/downloads
      - ./media/ebooks:/media/ebooks
    ports:
      - 8787:8787
    networks:
      - internal
    restart: unless-stopped

  # Joal for torrent
  joal:
    image: anthonyraymond/joal:latest
    container_name: joal
    restart: unless-stopped
    volumes:
      - ./joal:/data
    ports:
      - 9001:9001
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=9001", "--joal.ui.path.prefix=admin", "--joal.ui.secret-token=sqiydgqsyugfd@qsdui"]

  uptime-kuma:
    restart: always
    ports:
        - 3001:3001
    volumes:
        - ./uptime-kuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1

networks:
  internal:
    driver: bridge

